---
# Jenkins Agent Configuration Variables
aws_region: "us-east-1"
eks_cluster_name: "expense-dev"
aws_account_id: "589389425618"
domain_name: "vosukula.online"

# Java
java_package: "java-21-openjdk"
java_devel_package: "java-21-openjdk-devel"

# Jenkins
jenkins_url: "https://jenkins.vosukula.online"
jenkins_agent_name: "jenkins-agent"
jenkins_agent_workdir: "/home/ec2-user/jenkins-agent"

# SonarQube Scanner
sonar_scanner_version: "5.0.1.3006"
sonar_scanner_url: "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-{{ sonar_scanner_version }}-linux.zip"
