FROM jenkins/inbound-agent:latest

USER root

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    docker.io

# AWS CLI
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

# kubectl
RUN curl -LO "https://dl.k8s.io/release/v1.33.0/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/

# Terraform
RUN curl -LO https://releases.hashicorp.com/terraform/1.14.5/terraform_1.14.5_linux_amd64.zip && \
    unzip terraform_1.14.5_linux_amd64.zip && \
    mv terraform /usr/local/bin/

# Helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

USER jenkins